# clRole-admin.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin_app
rules:
# Управление подами, деплойментами, сервисами
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["*"]
# Управление неймспейсами и квотами
- apiGroups: [""]
  resources: ["namespaces", "resourcequotas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Доступ к событиям
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
